project_name: odoo-manager

before:
  hooks:
    - go mod tidy
    - go install github.com/a-h/templ/cmd/templ@latest
    - templ generate

builds:
  - main: ./cmd/odoo-manager
    binary: odoo-manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: jota2rz
    name: odoo-manager
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
