version: 2

project_name: odoo-manager

before:
  hooks:
    - go install github.com/a-h/templ/cmd/templ@latest
    - templ generate
    - >-
      sh -c 'if [ ! -f ./bin/tailwindcss ]; then
        mkdir -p bin &&
        OS=$(uname -s | tr "[:upper:]" "[:lower:]") &&
        ARCH=$(uname -m) &&
        if [ "$ARCH" = "x86_64" ]; then ARCH="x64"; elif [ "$ARCH" = "aarch64" ]; then ARCH="arm64"; fi &&
        curl -sLo bin/tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-$OS-$ARCH &&
        chmod +x bin/tailwindcss;
      fi'
    - ./bin/tailwindcss -i src/css/input.css -o cmd/odoo-manager/static/css/style.css --minify
    - go mod tidy

builds:
  - main: ./cmd/odoo-manager
    binary: odoo-manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: jota2rz
    name: odoo-manager
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
